import type { JourneyOption, JourneySearchInput } from './types';

export function getMockJourneyOptions(input: JourneySearchInput): JourneyOption[] {
  const date = new Date(`${input.travelDate}T00:00:00+05:30`);
  const perTraveler = (rupees: number) => rupees * 100 * input.travelers;
  const at = (dayOffset: number, hour: number, minute = 0) => {
    const value = new Date(date);
    value.setDate(value.getDate() + dayOffset);
    value.setHours(hour, minute, 0, 0);
    return value.toISOString();
  };
  const lastCheckedAt = '2026-07-03T09:30:00.000Z';

  return [
    {
      id: 'hyd-goa-train-konkan-demo',
      mode: 'train',
      provider: 'Indian Railways demo fare',
      departure: at(0, 6, 15),
      arrival: at(0, 20, 35),
      durationMinutes: 860,
      waitingTimeMinutes: 45,
      transfers: 1,
      baseFareMinor: perTraveler(850),
      taxesMinor: 0,
      baggageCostMinor: 0,
      firstMileCostMinor: perTraveler(250),
      lastMileCostMinor: perTraveler(300),
      totalEstimatedCostMinor: perTraveler(1400),
      comfortScore: 64,
      convenienceScore: 58,
      reliabilityScore: 72,
      flexibilityScore: 76,
      safetyGuidanceScore: 78,
      dataStatus: 'demo_estimate',
      lastCheckedAt,
      cancellationPolicy: 'Estimated refundable rules vary by ticket class. Verify before booking.',
      safetyGuidance: 'Use official stations, keep luggage close, and verify platform details live.',
      segments: [
        {
          mode: 'train',
          provider: 'Indian Railways',
          origin: input.origin,
          destination: input.destination,
          departure: at(0, 6, 15),
          arrival: at(0, 20, 35),
          durationMinutes: 860,
        },
      ],
    },
    {
      id: 'hyd-goa-bus-overnight-demo',
      mode: 'bus',
      provider: 'Private AC sleeper demo',
      departure: at(0, 20, 45),
      arrival: at(1, 9, 15),
      durationMinutes: 750,
      waitingTimeMinutes: 30,
      transfers: 0,
      baseFareMinor: perTraveler(1200),
      taxesMinor: perTraveler(60),
      baggageCostMinor: 0,
      firstMileCostMinor: perTraveler(220),
      lastMileCostMinor: perTraveler(350),
      totalEstimatedCostMinor: perTraveler(1830),
      comfortScore: 58,
      convenienceScore: 62,
      reliabilityScore: 60,
      flexibilityScore: 52,
      safetyGuidanceScore: 62,
      dataStatus: 'demo_estimate',
      lastCheckedAt,
      cancellationPolicy: 'Often partially refundable before departure. Verify operator rules.',
      safetyGuidance: 'Prefer known operators, share trip details, and use official pickup points.',
      segments: [
        {
          mode: 'bus',
          provider: 'Private AC sleeper demo',
          origin: input.origin,
          destination: input.destination,
          departure: at(0, 20, 45),
          arrival: at(1, 9, 15),
          durationMinutes: 750,
        },
      ],
    },
    {
      id: 'hyd-goa-flight-demo',
      mode: 'flight',
      provider: 'IndiGo / Air India demo',
      departure: at(0, 8, 10),
      arrival: at(0, 9, 35),
      durationMinutes: 85,
      waitingTimeMinutes: 145,
      transfers: 0,
      baseFareMinor: perTraveler(4200),
      taxesMinor: perTraveler(650),
      baggageCostMinor: perTraveler(900),
      firstMileCostMinor: perTraveler(450),
      lastMileCostMinor: perTraveler(700),
      totalEstimatedCostMinor: perTraveler(6900),
      comfortScore: 82,
      convenienceScore: 76,
      reliabilityScore: 78,
      flexibilityScore: 42,
      safetyGuidanceScore: 82,
      dataStatus: 'demo_estimate',
      lastCheckedAt,
      cancellationPolicy: 'Low-fare tickets may have limited refunds. Verify airline terms.',
      safetyGuidance: 'Verify baggage rules, airport reporting time, and flight status live.',
      segments: [
        {
          mode: 'flight',
          provider: 'Demo direct flight',
          origin: input.origin,
          destination: input.destination,
          departure: at(0, 8, 10),
          arrival: at(0, 9, 35),
          durationMinutes: 85,
        },
      ],
    },
    {
      id: 'hyd-goa-cab-demo',
      mode: 'cab',
      provider: 'Outstation cab demo',
      departure: at(0, 5, 30),
      arrival: at(0, 19, 0),
      durationMinutes: 810,
      waitingTimeMinutes: 0,
      transfers: 0,
      baseFareMinor: 26_000_00,
      taxesMinor: 1_300_00,
      baggageCostMinor: 0,
      firstMileCostMinor: 0,
      lastMileCostMinor: 0,
      totalEstimatedCostMinor: 27_300_00,
      comfortScore: 78,
      convenienceScore: 92,
      reliabilityScore: 68,
      flexibilityScore: 86,
      safetyGuidanceScore: 70,
      dataStatus: 'demo_estimate',
      lastCheckedAt,
      cancellationPolicy: 'Usually flexible until driver assignment. Verify cab provider policy.',
      safetyGuidance: 'Use verified operators, take breaks, and avoid fatigued night driving.',
      segments: [
        {
          mode: 'cab',
          provider: 'Outstation cab demo',
          origin: input.origin,
          destination: input.destination,
          departure: at(0, 5, 30),
          arrival: at(0, 19, 0),
          durationMinutes: 810,
        },
      ],
    },
    {
      id: 'hyd-goa-mixed-train-cab-demo',
      mode: 'mixed',
      provider: 'Train plus local cab demo',
      departure: at(0, 6, 15),
      arrival: at(0, 21, 15),
      durationMinutes: 900,
      waitingTimeMinutes: 70,
      transfers: 2,
      baseFareMinor: perTraveler(780),
      taxesMinor: perTraveler(40),
      baggageCostMinor: 0,
      firstMileCostMinor: perTraveler(180),
      lastMileCostMinor: perTraveler(450),
      totalEstimatedCostMinor: perTraveler(1450),
      comfortScore: 66,
      convenienceScore: 64,
      reliabilityScore: 70,
      flexibilityScore: 72,
      safetyGuidanceScore: 76,
      dataStatus: 'demo_estimate',
      lastCheckedAt,
      cancellationPolicy: 'Train and cab components have separate cancellation rules.',
      safetyGuidance: 'Build transfer buffer and verify local cab pickup points before arrival.',
      segments: [
        {
          mode: 'train',
          provider: 'Indian Railways demo',
          origin: input.origin,
          destination: 'Madgaon',
          departure: at(0, 6, 15),
          arrival: at(0, 19, 55),
          durationMinutes: 820,
        },
        {
          mode: 'cab',
          provider: 'Local cab demo',
          origin: 'Madgaon',
          destination: input.destination,
          departure: at(0, 20, 25),
          arrival: at(0, 21, 15),
          durationMinutes: 50,
        },
      ],
    },
  ];
}
