import type { HiddenCostItem } from './types';

const updatedAt = '2026-07-03T09:00:00.000Z';

export const hyderabadGoaHiddenCosts: HiddenCostItem[] = [
  {
    id: 'demo-ticket-base-fare',
    name: 'Hyderabad to Goa round-trip base fare',
    category: 'ticket_base_fare',
    amountMinor: 22_000_00,
    currency: 'INR',
    status: 'estimated',
    confidence: 'medium',
    explanation: 'Estimated flight base fare for four travelers before taxes and platform fees.',
    dataSource: 'Demo journey estimate',
    lastUpdatedAt: updatedAt,
  },
  {
    id: 'demo-taxes',
    name: 'Airline taxes and charges',
    category: 'taxes',
    amountMinor: 3_600_00,
    currency: 'INR',
    status: 'estimated',
    confidence: 'medium',
    explanation: 'Typical tax component shown separately from the ticket base fare.',
    dataSource: 'Demo journey estimate',
    lastUpdatedAt: updatedAt,
  },
  {
    id: 'demo-convenience',
    name: 'Booking convenience fees',
    category: 'convenience_fees',
    amountMinor: 1_000_00,
    currency: 'INR',
    status: 'estimated',
    confidence: 'high',
    explanation: 'Expected platform or payment fee for a group booking.',
    dataSource: 'Demo fee estimate',
    lastUpdatedAt: updatedAt,
  },
  {
    id: 'demo-baggage',
    name: 'Extra baggage buffer',
    category: 'baggage',
    amountMinor: 2_000_00,
    currency: 'INR',
    status: 'estimated',
    confidence: 'low',
    explanation: 'Optional buffer in case one traveler needs extra baggage.',
    dataSource: 'Demo baggage assumption',
    lastUpdatedAt: updatedAt,
  },
  {
    id: 'demo-first-mile',
    name: 'Cabs to Hyderabad airport',
    category: 'first_mile_transport',
    amountMinor: 1_600_00,
    currency: 'INR',
    status: 'estimated',
    confidence: 'high',
    explanation: 'Two cabs from home areas to the airport.',
    dataSource: 'Demo local transport estimate',
    lastUpdatedAt: updatedAt,
  },
  {
    id: 'demo-last-mile',
    name: 'Goa airport to stay',
    category: 'last_mile_transport',
    amountMinor: 2_200_00,
    currency: 'INR',
    status: 'estimated',
    confidence: 'medium',
    explanation: 'One larger cab or two regular cabs from the airport to North Goa.',
    dataSource: 'Demo local transport estimate',
    lastUpdatedAt: updatedAt,
  },
  {
    id: 'demo-local-transport',
    name: 'Scooters and local cabs',
    category: 'local_transport',
    amountMinor: 4_800_00,
    currency: 'INR',
    status: 'estimated',
    confidence: 'medium',
    explanation: 'Four-day mix of scooter rental, fuel, and short cab rides.',
    dataSource: 'Demo itinerary estimate',
    lastUpdatedAt: updatedAt,
  },
  {
    id: 'demo-accommodation',
    name: 'Shared apartment stay',
    category: 'accommodation',
    amountMinor: 12_000_00,
    currency: 'INR',
    status: 'estimated',
    confidence: 'medium',
    explanation: 'Three nights in a modest shared apartment for four travelers.',
    dataSource: 'Demo accommodation estimate',
    lastUpdatedAt: updatedAt,
  },
  {
    id: 'demo-food',
    name: 'Food and cafes',
    category: 'food',
    amountMinor: 8_000_00,
    currency: 'INR',
    status: 'estimated',
    confidence: 'medium',
    explanation: 'Moderate food plan including breakfasts, lunches, and casual dinners.',
    dataSource: 'Demo itinerary estimate',
    lastUpdatedAt: updatedAt,
  },
  {
    id: 'demo-activities',
    name: 'Beach clubs and activities',
    category: 'activities',
    amountMinor: 4_500_00,
    currency: 'INR',
    status: 'estimated',
    confidence: 'low',
    explanation: 'Flexible activity spend for beach shacks, nightlife covers, and small experiences.',
    dataSource: 'Demo itinerary estimate',
    lastUpdatedAt: updatedAt,
  },
  {
    id: 'demo-internet',
    name: 'Backup SIM and data',
    category: 'internet_or_sim',
    amountMinor: 500_00,
    currency: 'INR',
    status: 'estimated',
    confidence: 'high',
    explanation: 'Small connectivity buffer for one backup data pack.',
    dataSource: 'Demo connectivity estimate',
    lastUpdatedAt: updatedAt,
  },
];
